version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu
    overwrite: yes

file_exists_behavior: OVERWRITE    

permissions:
  - object: /home/ubuntu
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 3600
      runas: ubuntu

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 3600
      runas: ubuntu
